# -*- coding: utf-8 -*-
"""Лабораторная№1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12i0DjDRXPx64IeQ5IbNOV159lOD5sSbT
"""

print("Hello World")

a = int(input())
b = int(input())
print(((a ** 3 + 14) // 5) * b)

a = int(input())
n = int(input())
print(a ** 2 // n)

a = float(input())
b = float(input())
c = int(input())
d = int(input())
print(a // b)
print(c * d)
print(c % d)

a = 1
b = 4
c = a + b
print(c)

a = float(input())
h = int(input())
s = (a*h)/2
print(s)



a = 5
b = int(input())
c = a * b
print(c)

a = int(input())
b = int(input())
print((a + b) ** 2)

a = 15
b = 10
c = int(input())
print((a + b)//c)

a = int(input())
b = int(input())
print(a, '**2+', a, '*', b, '*2+', b, '**2', sep='')

a = float(input())
b = float(input())
print(a // b)

a = int(input())
b = int(input())
print(a * b)

a = 10
b = 3
print(a % b)